export const GET_STOCK_SUCCESS = "GET_STOCK_SUCCESS"
export const GET_STOCK_FAILED = "GET_STOCK_FAILED"
export const GET_STOCK_REQUESTED = "GET_STOCK_REQUESTED"


export const GET_WATCHLIST_SUCCESS = "GET_WATCHLIST_SUCCESS"
export const GET_WATCHLIST_FAILED = "GET_WATCHLIST_FAILED"
export const GET_WATCHLIST_REQUESTED = "GET_WATCHLIST_REQUESTED"
